language: node_js
node_js:
  - "10.16.0"
cache: yarn
addons:
  chrome: stable
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.5.1
  - export PATH="$HOME/.yarn/bin:$PATH"
